### ISSUE TITLE
Add Timestamp Opcode

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuel-specs#220]
# Motivation
Currently, the FuelVM spec does not include a timestamp. This is for many practical reasons, namely, that we do not know when the block will be produced precisely and thus a timestamp could be manipulated quite heavily.

# Solution
I propose a timestamp opcode `timestamp` which is enforced by by using both the underlying layer-1 chain and by checking the previous blocks stamp.

The timestamp for each Fuel block must be both within 30 minutes of the underlying related Ethereum block (included in the header), and greater than the previous Fuel blocks posted timestamp.

# Note
The timestamp should not be relied upon for highly precision oriented use-cases which need more than 30 minutes of precision. But for many general uses cases (i.e. vesting schedules etc), this would work quite well.

# Opcode
I expect the opcode to only be a single op with no arguments. Similar to the block number op.

**Comment by dmihal** [comment]
Hey, was just discussing this feature with @adlerjohn, and wanted to post here to give some context on why a timestamp is needed.

The simplest usecase would be a token that's vesting over a period of time. Since there's no assurances about the time between blocks, the sequencers could be potentially bribed to speed-run a bunch of empty blocks, vesting a token early.

Similarly, most DAOs have some sort of timelock, which prevents actions from being executed before a window has elapsed.

The more complex use case (the one where I ran into this issue) is a TWAP (time weighted average price) oracle, which provides manipulation-resistant price data from an AMM.
