### ISSUE TITLE
Log Data with Immediate Length (LGDI)

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-specs#279]
LGDI will log the range `MEM[$rA, imm]`

There are many cases where the length is statically known ahead of time, such as logging a 32 byte address, contract id, or storage value. In these cases, it would be more convenient and potentially faster if there was a LGDI instruction that takes the length as an immediate value (e.g. 32), rather than being loaded indirectly to a register.

|       | Description |
| ----------- | ----------- |
| Operation   | ```log(MEM[$rA, imm]);```
| Syntax      | `lgdi $rA, imm`
| Encoding    | `0x00 rA i i i`

**Comment by adlerjohn** [comment]
🤔 this would either require:

1. Adding two register value parameters and restricting the immediate to 6 bits (which would be sufficient for the usecase of logging hashes, which presumably could happen a lot).
2. Removing the two register value parameters from `LOGD`, so that the same receipt can be re-used for both.
3. Add a new receipt type for this instruction, different from the `LOGD` receipt.

Thoughts? @Voxelot and I'll cc @digorithm and @sezna too.

**Comment by digorithm** [comment]
Yeah, for the cases where we know the length it's better if we just pass the immediate value. I like John's `(2)` because adding more receipt types will definitely cause more complexity downstream.

**Comment by Voxelot** [comment]
With (2) we'd be able to use 18bit immediate values since the structure would be similar to opcodes like `MCLI`.

**Comment by adlerjohn** [comment]
There hasn't been any demand for this feature. And the Sway stdlib uses generics with variable sizes.
