### ISSUE TITLE
Widen tx field counts to 64 bits

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#298]
8 and 16 bits are used throughout, but are too small.

**Comment by AlicanC** [comment]
One issue with u64 for lengths & counts is that we can't represent these easily in JS. A recent update I've made got rid of a lot of ugliness because we were finally using `number`s for sizes <64:

```ts
const myArray = [1, 2, 3];

// Before with u16 (or would be the same with u32)
new ArrayEncoder(new NumberCoder('u64'), BigInt(myArray.length)).encode(myArray);

// After with u64
new ArrayEncoder(new NumberCoder('u64'), myArray.length).encode(myArray);
```

This isn't an issue for non-count non-size stuff since they can exist as they are, but for counts/sizes we need to go from number to bigint constantly because JS always uses number for lengths.

Can we keep these as u32s?

**Comment by adlerjohn** [comment]
In practice, most of these fields won't exceed the limit of a `u32` even if their _type_ is `u64`. There will be consensus rules placing an upper bound on each of these fields that will be well below the maximum `u64` (or even the `maximum `u32`) value. Is that sufficient @AlicanC, or does the _type_ need to be `u32`?

**Comment by AlicanC** [comment]
If the type is u32 the coding infra will just handle it naturally. Otherwise we will have to introduce a concept of `things that are defined as u64 but should be treated as u32 for convenience` and have code to handle that.

**Comment by MitchTurner** [comment]
I think `u16` should be enough. Can we close this @xgreenx ?

**Comment by xgreenx** [comment]
Yeah, `u16` sound good for 1 second blocks for now
