### ISSUE TITLE
Lengths must be checked to match

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#357]
There are currently no requirements that lengths match the length/number of elements for transaction variable-length fields. They must match for the tx to be valid.

**Comment by vlopes11** [comment]
I don't see how that can be an attack vector since the length is set upon VM initialization. Any inconsistency there would be a VM bug, and not a malformed tx.

Is there any potential attack I'm not seeing? Or is it to protect raw bytes that are canonical serializations of a tx to be inconsistent outside VM contexts?

I think it would be nice to add a comment to the specs illustrating the potential threats so if others have the same questions as I do, they could just check the specs.
