### ISSUE TITLE
Consider introducing relative jumps.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/fuel-specs#430]
The https://github.com/sway-libs/amm library is an example of a very large contract.  Even if we continue to improve the compiler optimisations its binary will always be multiple megabytes in size.

This has caused an issue outlined in https://github.com/FuelLabs/sway/issues/3161.   For conditional jumps we have a limited absolute address we can jump to -- 18bits (256K instructions or 1MB) for `JNZI` and 12bits (4K instructions or 16KB) for `JNEI`.  I introduced dynamic jumps using the `JMP` and `JNE` instructions in https://github.com/FuelLabs/sway/pull/3109 for jumps with addresses which don't fit in those immediates, where the addresses are instead loaded from the 'data section' (initialised const data baked into the binary).

The `amm` library currently compiles to around a 3.7MB binary.  All of the control flow in that binary above the 1MB mark uses dynamic jumps to addresses loaded from the binary.  So this has added 19,700 words to the data section, making it about 160KB in size (where there is only about 2KB of actual const data introduced by the contract itself).  It also implies that there are _at least_ 19.700 runtime jumps which require two instructions; the load and the dynamic jump.

Apart from the initial jump using the contract method selector, I think essentially all conditional control flow is localised to within functions.  Basic `if` or `match` expressions or `while` loops.  I imagine all of them would be local enough to fit in an 18bit _relative_ jump offset, a vast majority would probably fit in 12bits.

If we were to add instructions for relative conditional jumps I think all of the above inefficiencies would go away.  We wouldn't need 19K addresses to be stored in the data section and all the local control flow would be back to a single instruction rather than 2 (or more, depending on the binary size).

Some of this is conjecture but I could add some analysis to the compiler to confirm exactly the impact using relative jumps would provide, given this is an acceptable proposal.

**Comment by adlerjohn** [comment]
Those gains don't seem massive in the grand scheme of things: 160 KB in a 3.7 MB binary. FWIW, with proper optimizations the binary size shouldn't be more than a megabyte. Those same contracts on Ethereum should be less than a megabyte in size.

W.r.t. your suggestion, it's specifically relative _immediate_ jumps, not relative dynamic jumps, right? Regardless, it would require four new instructions: two on conditional/unconditional and two on forwards/backwards. That would put us at eight instructions just for jumps, which seems like a lot, but I don't know.

**Comment by otrho** [comment]
> Those gains don't seem massive in the grand scheme of things: 160 KB in a 3.7 MB binary. FWIW, with proper optimizations the binary size shouldn't be more than a megabyte. Those same contracts on Ethereum should be less than a megabyte in size.

It seems a bit egregious when only 2k is actually data and the rest is almost 20,000 addresses.  And it's the only reason at the moment that https://github.com/FuelLabs/sway/issues/3161 is necessary.

For the worst case each local jump in these far off functions we need to `LW` the data section for the address, `LW` the address itself, `ADD` `$is` to it and then jump with `JNE` or `JMP`.  Four instructions which could be just one, two of which are memory accesses.

With a bit of effort we could try to make all the addresses in a local function use the same data section and that would reduce it to a best case of three instructions to jump to any address beyond 1MB.

> W.r.t. your suggestion, it's specifically relative _immediate_ jumps, not relative dynamic jumps, right? Regardless, it would require four new instructions: two on conditional/unconditional and two on forwards/backwards. That would put us at eight instructions just for jumps, which seems like a lot, but I don't know.

No, I'm thinking we need only two or even one.  Yep, they're immediate, but we don't need unconditional relative jumps because `JI` has a 24bit address which allows for a 64MB binary.  And there's no reason why the jump offset can't be signed, is there?  So we'd need `JNZRI` at the very least and `JNERI` too.

**Comment by otrho** [comment]
Noting here the realisation also that relative jumps are required for position independent code which in turn would be extremely helpful for code loading via `LDC`.

**Comment by Dentosal** [comment]
Here is a proposal on how the jump instructions could look.

## Limitations of the current model

The current version doesn't support relative jumps at all. This is the reason we have this issue in the first place.

The varying and rather small immediate size in jump instructions is making things rather complicated as well. JNZI has a 18bit offset, allowing about 1 MiB of code. JNEI has only 12bits for the immediate, meaning that it cannot be after the first 15 KiB. Since the contract size is limited to 16 MiB currently, these jumps are not usable in the larger contracts at all.

## Theory

A jump operation consists of the following parts

* Condition: unconditional, compare one register to zero, compare two registers
* Target operand: with or without register
* Immediate offset: signed or unsigned
* Absolute or relative

All combinations of these are sensible operations. In addition, relative jumps could be separated to backwards and forward jump to avoid signed "pointer" arithmetic. However, having 24 or so different jump instructions doesn't seem sensible. (Although we do have enough opcodes for that, if desired.)

When the condition is fullfilled, a jump does this `$pc = base + (reg_offset + imm_offset) * 4` where:

* `base` is `$is` for absolute jumps, and `$pc` for relative jumps.
* `reg_offset` is the offset from a target register, or none if that input is not given
* `imm_offset` is the offset from the immediate part of the operation

Signedness of the operands matters as well. For absolute jumps, the register value is naturally unsigned, an jumping to an instruction before $is is not sensible. The immediate can be signed or unsigned, that doesn't make much difference. For relative jumps, however, there are three options:

1. Have separate opcodes for forwards and backwards jumps, so all operands are unsigned.
2. The immediate value is signed, and the (otherwise unsigned) register is assumed to have the same sign as the immediate operand.
3. Both values are signed.


## Picking sensible options

I'm picking some generaly sensible options here. If some other set of options is better for compiler developers, for instance not wanting to deal with signedness, different set of operations could be chosen.

After doing the reasonable division between encoding in opcode and arguments, we have the following opcodes:

Instruction                 | Condition     | Target (`$pc` value after)
----------------------------|---------------|--------------------------
`JMPA $target imm18`        | Unconditional | `$is + $target + signed(imm)) * 4`
`JMPR $target imm18`        | Unconditional | `$pc + (signed($target) + signed(imm)) * 4`
`JNZA $nzcond $target imm12`| Nonzero       | `$is + ($target + signed(imm)) * 4`
`JNZR $nzcond $target imm12`| Nonzero       | `$pc + (signed($target) + signed(imm)) * 4`
`JEQA $rA $rB $target imm6` | Equality      | `$is + ($target + signed(imm)) * 4`
`JEQR $rA $rB $target imm6` | Equality      | `$pc + (signed($target) + signed(imm)) * 4`
`JMPAF imm24`               | Unconditional | `$pc + imm * 4`
`JMPRF imm24`               | Unconditional | `$is + signed(imm) * 4`
`JNZRF $nzcond imm18`       | Nonzero       | `$is + signed(imm) * 4`
`JEQRF $rA $rB imm12`       | Comparsion    | `$is + signed(imm) * 4`

Where `signed` reads value in two's complement format.

(Names open for bikeshedding of course. The current format is `Jcc[AR]F?` where `cc` is condition, `A|R` means either absolute or relative, and `F` in the end menas fixed offset, i.e. no target register operand.)

## Alternatives

We could remove some or all `JEQ*` operations, since the immediate part for them is rather small. `JEQ($a, $b, ...)` can be emulated with `XOR($tmp, $a, $b); JNZ($tmp, ...)`.

**Comment by otrho** [comment]
Cool, thanks for spec'ing this out @Dentosal.  A couple of notes:

- I personally didn't mind the idea of signed offsets but there was always a lot of pushback on the idea, basically because we don't have signed values anywhere else in the entire VM spec.
- I'm not sure how useful having a `$target` _and_ `imm` in the single instruction is, as fas as the compiler is concerned.  This is especially true for relative conditional jumps which really only need a relative `imm` and if it could be 6-bits wider that would probably be more useful.
- I have a feeling the conditional absolute instructions would never be used.  To accommodate PIC the compiler will be emitting relative jumps for all control flow.  So I can't really think of a need for absolute addressing any more, other than for the basic `JI` (`JMPAF`) and `JMP` (`JMPA`) instructions which we already have.  If the plan is to keep the older instructions to remain backward compatible with the current betas then we only need new relative jump instructions.

So on that last point, do we plan to keep the current jump instructions (perhaps rename them) and only add new relative jump instructions?

**Comment by Dentosal** [comment]
The point of having both $target and immediate operand is that the immediate operand is something we get for free, since those bits would go unused otherwise. That also helps to unify the instruction format. The primary use case for relative

However, if signed offset are something we don't want, we could simply duplicate the relative operations to make backwards and forwards jumping variants. For instance, we could have:

Instruction                 | Condition     | Target (`$pc` value after)
----------------------------|---------------|--------------------------
`JMPRB $target imm18`        | Unconditional | `$pc - ($target + imm) * 4`
`JNZRB $nzcond $target imm12`| Nonzero       | `$pc - ($target + imm) * 4`
`JEQRB $rA $rB $target imm6` | Equality      | `$pc - ($target + imm) * 4`
`JMPRF $target imm18`        | Unconditional | `$pc + ($target + imm) * 4`
`JNZRF $nzcond $target imm12`| Nonzero       | `$pc + ($target + imm) * 4`
`JEQRF $rA $rB $target imm6` | Equality      | `$pc + ($target + imm) * 4`

And possible also variants without `$target`.

Really, I'd like to have something like x86 flags register so that the previous operations could set flags, so that we don't have to include register refences to jump instructions, giving us more immediate space. Also implicit register arguments would help with that. On the other hand, I really like the simplicity of the current design, but on the other hand it feels like wasted potential.

**Comment by otrho** [comment]
Yep, fair enough, for 'dynamic' jumps which need a register, they might as well use the spare instruction space as an immediate.  Makes sense.  As long as there is still a 'fixed' version still which only takes an immediate address.

And I think having pairs of forwards and backwards instructions as above is preferred by most people.

Yeah, conditional jumps based on flags might be nice, but I guess conditional dynamic jumps are fairly similar.  It's kind of:
```asm
    cmp r0, r1              ; set flag
    jeq <far 18bit address> ; jump based on flag
```
vs
```asm
    mov r2, <far 18bit address>
    jeq r0, r1, r2          ; jump by direct comparison
```

**Comment by adlerjohn** [comment]
Pitching in to say I'm in camp having separate instructions for jumping forward and backward, because there are no signed numbers anywhere in the VM.

**Comment by Dentosal** [comment]
Closing in favor of #470
